#!/usr/bin/env python3
'''
MIT License

Copyright (c) 2023 github.com/DeaSTL

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
'''
import os
import subprocess
import tempfile
import shutil

def extract_audio(mp4_file, temp_dir, output_dir):
    base_name, ext = os.path.splitext(mp4_file)
    opus_file = os.path.join(temp_dir, base_name + '.opus')
    output_file = os.path.join(output_dir, base_name + '_opus_encoded.mp4')
    command = ['ffmpeg', '-i', mp4_file, '-vn', '-c:a', 'libopus', opus_file]
    subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    
    command = ['ffmpeg', '-i', mp4_file, '-i', opus_file, '-c', 'copy', '-map', '0:v', '-map', '1:a', output_file]
    subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def main():
    current_dir = os.getcwd()
    print(f"Working directory: {current_dir}")

    # Create temporary directory for Opus files
    temp_dir = tempfile.mkdtemp()
    print(f"Temporary directory: {temp_dir}")

    # Create output directory for combined files
    output_dir = os.path.join(current_dir, 'output')
    os.makedirs(output_dir, exist_ok=True)
    print(f"Output directory: {output_dir}")

    # Get the list of mp4 files in the current directory
    mp4_files = [file for file in os.listdir() if file.lower().endswith('.mp4')]

    for mp4_file in mp4_files:
        extract_audio(mp4_file, temp_dir, output_dir)

    # Delete the temporary directory
    shutil.rmtree(temp_dir)
    print("Audio extraction and combination complete. Temporary directory deleted.")

if __name__ == '__main__':
    main()
